### ISSUE TITLE
How to get serial port "printf" style support..

### ISSUE THREAD

**Issue by bmentink** [maxgerhardt/wizio-pico#2]
Hi,
This platform works fine for building and uploading, but how do I get it to support monitor mode in PlatformIO so that
you gan do simple printf()'s 

Any idea's?

**Comment by maxgerhardt** [comment]
The picosdk example literally has a `printf()`

https://github.com/maxgerhardt/wizio-pico/blob/main/examples/picosdk-blinky/src/main.cpp

the Arduino core is so incomplete that you should not use it. Use the regular https://github.com/platformio/platform-raspberrypi/ platform and Arduino example so that you have `Serial` and `Serial.printf()`, it uses the https://github.com/arduino/ArduinoCore-mbed.

**Comment by bmentink** [comment]
Hi,
Thanks, printf did not work till I put the following in platformio.ini, now
it works great. I don't want to use Arduino, I have some existing SDK based
code that I wanted to compile with platformio, works great.
`monitor_speed = 115200

build_flags = -D PICO_STDIO_USB ;
`

Cheers

**Comment by maxgerhardt** [comment]
I see, but that's then already contained in 

https://github.com/maxgerhardt/wizio-pico/blob/ae2e5fbf4e7fb29eea8555fe3dc160441b818e7a/examples/picosdk-blinky/platformio.ini#L16-L18

**Comment by bmentink** [comment]
Yep, did see that, I guess I expected that option to be in platformio.ini
by default, no biggy ...
By the way, what SDK version is used?, I see the latest 1.5.0 has Bluetooth
support for the Pico W, will this
platform automatically upgrade the SDK?

Cheers
